### ISSUE TITLE
next magstock: change column type of attendee.campsite_number

### ISSUE THREAD

**Issue by binary1230** [magfest/magstock#103]
apparently we used a VARCHAR and should not have, remember to change it before bringing up next year's magstock registration

**Comment by kitsuta** [comment]
That was just a problem with the DB migration, it will be created correctly with a new instance.

**Comment by kitsuta** [comment]
Further info:

Alembic uses sqlalchemy Column types, but we use sqlalchemy Column types with sideboard and RAMS custom column types _on top of_ that. I haven't yet looked into if we can get Alembic fully 'hooked into' our system's concept of columns. If we can't, we'll just have to manually edit DB migrations to import sideboard and use our column types.

**Comment by binary1230** [comment]
ah ok gotcha
