### ISSUE TITLE
'Add attendee' page in at-the-con mode doesn't show un-bolded fields

### ISSUE THREAD

**Issue by binary1230** [magfest/magstock#12]
low pri half-assed bug report since i'm on-site at magstock

![image](https://cloud.githubusercontent.com/assets/5413064/8260899/803ab922-1694-11e5-8ce4-bd97d6d5c751.png)

Some of the fields shown there are optional like email and zip code and don't need to be entered during adding an attendee.

However, those fields are currently bolded, implying that they have to be filled in.

We should fix the fields so they become non-bold when they're optional

**Comment by binary1230** [comment]
this might be a general ubersystem issue and not magstock-specific, probably needs to get moved to magfest/ubersystem instead of here

**Comment by kitsuta** [comment]
Yes. There may actually already be an issue in the main repo, not sure.

**Comment by binary1230** [comment]
This issue was moved to magfest/ubersystem#1852
