### ISSUE TITLE
Noise levels - on Registration page.

### ISSUE THREAD

**Issue by bds002** [magfest/magstock#23]
Per the MAGStock 6 planning meeting, there where going to 5 noise levels this year:
This was in the .ini file at one point, but is not currently there.

quiet:   "As quiet as possible at night"
conversational: "I can sleep when people talk"
normal:  "I can sleep through reasonable levels of noise"
noisy:   "While others sleep, I PARTY!"
WUAAAGAAAAHHH: "I can't get enough WUAAAGAAAHHH in my life"

**Comment by binary1230** [comment]
this is part of an open PR which has not yet been merged, so it won't be in the INI until the following is merged in: https://github.com/magfest/production-config/pull/4/files

**Comment by kitsuta** [comment]
I've merged the PR that implements this, but I can't test it yet, so I'm holding off on closing this issue until then.

**Comment by kitsuta** [comment]
Okay, I've deployed to staging and checked, and the new options are there now. Closing as fixed.
