### ISSUE TITLE
feature request: Add food option to badge levels

### ISSUE THREAD

**Issue by kitsuta** [magfest/magstock#29]
We want to promote the ability to buy food, so it should be added to the badge levels.

@bds002 - if I can do this, should the checkbox itself be hidden or do we want to keep that redundancy?

**Comment by kitsuta** [comment]
Having just made this issue, I realize there's a problem with it. Badge level options are programmed to be mutually exclusive, but the food option layers over top of the kick-in levels.

Would it be okay if we did something else to 'highlight' the food option? I can move it up the page, make it a big ol' button, that sorta thing.

**Comment by bds002** [comment]
I think I responded to this inquiry in another forum, but that's fine.  I think what you did works well.

**Comment by kitsuta** [comment]
OK, I'll leave this issue up but take it off the pre-reg milestone.

**Comment by binary1230** [comment]
our current solution works well, bsmart agrees, we're gonna close this because it will also be really hard to change now that prereg is launched.

**Comment by kitsuta** [comment]
Well, not really, as it's just a front-end change. But I'm fine with not having to do anything. :P
