### ISSUE TITLE
Change: Registration Confirmation Email date....

### ISSUE THREAD

**Issue by bds002** [magfest/magstock#37]
The last paragraph of the registration email says that: "~ To transfer your registration to another person, send them this personalized link, which will work until 11:59pm EDT on Friday, Jun 17. "

This is after MAGStock starts, (Reg opens either Thurs the 16th or Fri. the 17th)
We shouldn't allow badge transfers while check-in is happening?

What has been the procedure/policy in the past?

Data in question: the date for that transfer question is c.UBER_TAKEDOWN

**Comment by kitsuta** [comment]
For Super MAG and Labs, we absolutely let people transfer badges during the fest. It saves us a lot of headache, and it's more convenient for them.

Keep in mind that once someone is checked in, they can't transfer their badge.

**Comment by bds002** [comment]
Vicki, I'm deferring to you on this one. I don't think the Stock Team is going to care one way or the other.  My comments where my first thought, but you know more about good reg work flow than I do. 
I consider this closed . :)
