### ISSUE TITLE
decide if we keep "under 18=waiver" text

### ISSUE THREAD

**Issue by binary1230** [magfest/magstock#38]
After finishing reg it says:

```Attendees under 18 MUST bring a signed parental consent form, which MUST be notarized if the parent is not attending the fest.```

Is this true for Magstock?

**Comment by kitsuta** [comment]
Tagging @bds002.

**Comment by bds002** [comment]
I didn't get a response from Charles on this, but I think for a consistency sake (Mag Inc events) we should leave it in place.  I don't expect that Stock is going to have but a couple <18 people that don't belong to either an attendee or a campground family.

**Comment by kitsuta** [comment]
OK, I'm going to close this - we can reopen if Charles wants to remove it. It's quick and easy.
