### ISSUE TITLE
maybe confusing button text on badge update/transfer page

### ISSUE THREAD

**Issue by binary1230** [magfest/magstock#39]
to repro:
1) reg and pay for a badge w/ support+shirt
2) click the confirmation link so you are on /uber/preregistration/confirm

observe:
![image](https://cloud.githubusercontent.com/assets/5413064/14901512/d838f96a-0d63-11e6-8b5f-57b36117f995.png)

Maybe I'm just being dumb but It looks like even though I ordered a shirt, it's still asking me if I would like to "add a shirt".

Not sure we need to fix this before magstock reg opens, just an observation.

**Comment by kitsuta** [comment]
I'm taking it off the milestone, but yea it would be good to fix this so it displays everything properly.

**Comment by rscullin** [comment]
I had a similar issue.

I bought a ticket at the T-Shirt level; when I go to edit it from the link I got in my Email, I get this:

![image](https://cloud.githubusercontent.com/assets/176014/14960783/5b8ec4d6-1064-11e6-8de0-443b5bf34578.png)

Clicking the left "Add a tshirt" button doesn't do anything, and I don't have the option to upgrade to a full supporter badge.
