### ISSUE TITLE
revisit parking policies

### ISSUE THREAD

**Issue by binary1230** [magfest/magstock#40]
This is not a technical issue, there's still ongoing discussion about what the parking policy should be.

Currently says:
![image](https://cloud.githubusercontent.com/assets/5413064/14901796/37b458fc-0d65-11e6-8344-5e6df69662fa.png)

if we decide to change it, update the text here and in the confirmation email to reflect.

campground policy (which might be less restrictive than what we go with) is:
_"No more than two (2) motorized vehicles per site (the second vehicle may be required to be parked in our group parking area.) Additional vehicles will be charged $5/day and may not be used for inter-campground transportation."_

**Comment by binary1230** [comment]
@kitsuta already diligently changed it, so apologies if it gets changed again.  props to @kitsuta

**Comment by bds002** [comment]
Per Charles Lohr (Point on MAGStock): " If you really want you can sleep in your car in the free parking area!  It just means you won't be in the thick of things. / Other: The $20 was arbitrary, but I thought about it a while before coming to it.   @hachi There is NO WAY to enforce one car per site.  We tried last time, a LOT, but there were situations where two people would be in a site, both wanted a car, neither wanted to be the one who moved.  No one wants to be the ones who don't have the cars at their sites.   Every car that's in that area is less space for tents and people.  No cars = more people in the area = good for us and everyone. "

**Comment by kitsuta** [comment]
So wait, does this mean that you can't have a car even if you're sleeping in it, even though that's a site option? That's... confusing.

**Comment by bds002** [comment]
Charles is the lead on Stock and what I am thinking the work flow will be is that if you select car camping, we might have a closer designated area for that (Manor house or something).... but for now, he wants to leave it as is with the notification on no cars in the tent site areas.

**Comment by kitsuta** [comment]
Roger. Closing as decided - we can reopen if Magstock folks change their mind.
