### ISSUE TITLE
transferring badge error javascript error

### ISSUE THREAD

**Issue by binary1230** [magfest/magstock#42]
![image](https://cloud.githubusercontent.com/assets/5413064/14904054/92f0f136-0d73-11e6-8677-0c3832d222e5.png)

```Cannot read property 'parents' of null```

Might be related to or the cause of https://github.com/magfest/magstock/issues/41

**Comment by kitsuta** [comment]
Whoops, haha. I was so sure about Anthrocon's method of hiding the amount_extra field, but AC doesn't have any transferable badge types, so this was never caught.
