### ISSUE TITLE
add any event_location[s] needed for magstock

### ISSUE THREAD

**Issue by binary1230** [magfest/magstock#47]
Right now we have only 'concerts' in the /uber/schedule

Add anything we need in there like 'Events', 'SlipNSlide' etc.   differentiate between event locations (pavilion, concert tent, slipnslide, lake) vs events themselves (yoga, cookoff, particular bands, etc)

Magstock leadership / events crew should comment on this issue with what they want.

**Comment by kitsuta** [comment]
Closing this as fixed by https://github.com/magfest/production-config/pull/22.
