### ISSUE TITLE
Remove unneeded sections from magstock band checklist

### ISSUE THREAD

**Issue by cybersenshi** [magfest/magstock#57]
![fireshot_capture_1_-_magstock_-_band_information__-_https___localhost_4443_uber_bands_index](https://cloud.githubusercontent.com/assets/2566383/15216780/88900a7a-1826-11e6-9676-cec881972ca6.png)

**Comment by binary1230** [comment]
quick notes for @kitsuta: the files you need to modify are:
- plugin_bands.pp
- event-magstock.yaml
- band-development.ini.erb

I -believe- all you need to do is follow the example of the existing ```stage_agreement_deadline``` parameter in those files.  It's a bit of slightly tedious copy+paste but should be pretty easy.

to re-deploy puppet locally to test:
```
vagrant ssh
cd ~/uber/puppet
./apply_node.sh localhost
```

**Comment by binary1230** [comment]
also when editing band-development.ini.erb, just be careful of the section header ordering like ```[dates]```

other than that, same drill as usual.
