### ISSUE TITLE
As a magstock registration admin, I would like to pre-assign sites to attandees before getting on-site

### ISSUE THREAD

**Issue by bds002** [magfest/magstock#58]
When onsite @ Stock there is a manual process of look at the available sites and assigning attendee groups to the site, based on available sites and number of attendees in each Tent group / number of tents etc.

--The camp ground has an interactive map at : https://www.sunrisereservations.com/reservation/selectSiteCriteria?cgId=411

--That list all the sites, we also have a papercopy of all available sites under the MAGStock name.

-- There is an Admin-only field on the Attendee registration page that says: "Site Number" that is used on site plug in the information. This is the field I would like to fill in before event as much as possible.
@migetman9 has the drop down list I believe for this purpose.

**Comment by binary1230** [comment]
quick thing: when making these issues, it's helpful if an issue is easily distinguishable as something broken vs something that is new functionality.

To that end, for feature requests like this one, it's helpful if we follow the user story format like: "As a STOPs admin, I would like to pre-assign sites to attandees before getting on-site".  It's also helpful if (as you did here) you describe why this is an important thing and what problem it will solve.

There's a huge amount of stuff we could add in regarding campsites, maps, attendees, and it's helpful for our code team to have as much context as possible when prioritizing what gets done and what won't be able to get done, and also in figuring out which issues are ready to be coded vs issues that need more design or thought put into them.

**Comment by kitsuta** [comment]
Yeah, I have to say that I don't understand the coding change you want
here. You should be able to go to attendees right now and fill in their
sites.

**Comment by bds002** [comment]
I  want Uber to be able to tell me: 
- How many people are assigned to each site and how many more we can put in there. 
Currently there is no link that I am aware to show who's assigned to what site.... 

I see this along the lines of the Hotel plug in, but a little different.
@EliAndrewC is somewhat aware based on how things have been done onsite in the past.

**Comment by kitsuta** [comment]
OK, after further discussion with @bds002 I've found out that the change needed is that we need a _dropdown_ for the "camping site" field, populated via config as a list of the camp's sites. Admins should also be able to easily find people based on who they entered as their tent leader/coming with group.

**Comment by kitsuta** [comment]
Fixed by #89.
