### ISSUE TITLE
Print version of pages includes URLs

### ISSUE THREAD

**Issue by willmurnane** [magfest/magstock#67]
When I print [the food purchases page](https://magstock6.uber.magfest.org/uber/magstock/food_purchases) I get a bunch of cruft in the output:

(screenshot removed, had personal data -Dom)

Adding this CSS appears to fix the problem, without making problems elsewhere. Use at your own risk, I guess?

    a[href]:after {
       content:"" !important;
    }

**Comment by binary1230** [comment]
oh hey i totally fixed this already, and yea @willmurnane your fix worked great
