### ISSUE TITLE
When bands adds members, option of food is listed as a paid extra

### ISSUE THREAD

**Issue by binary1230** [magfest/magstock#74]
_From @pelololoquin on June 8, 2016 15:38_

![image](https://cloud.githubusercontent.com/assets/7318559/15900428/77bcb9d0-2d6d-11e6-8829-ddac540f5a1a.png)

_Copied from original issue: magfest/ubersystem#1848_

**Comment by pelololoquin** [comment]
Should not show up at all since food is included for bands and plus ones

**Comment by binary1230** [comment]
I think I have a fix for this, and also discovered that we are asking people with Staff badges (who get free food) if they also want to pay extra.  i think my fix will cover both cases decently.

**Comment by pelololoquin** [comment]
Since food is generally part of our band agreements and part of the compensation for playing, this might become an ongoing thing to note depending on how we do food at future events

**Comment by binary1230** [comment]
agreed, though food is usually handled very different (in code) from event to event, so will likely require customization on a per-event basis.  or at least, different between magstock and the rest of the events.
