### ISSUE TITLE
check if at-door pricing correct / are we offering single days?

### ISSUE THREAD

**Issue by binary1230** [magfest/magstock#82]
Talk to magstock team and figure out if all this looks correct or if it needs adjustment:

![image](https://cloud.githubusercontent.com/assets/5413064/15969320/8e1c7db4-2efd-11e6-80cc-4e57814bcc69.png)

**Comment by cnlohr** [comment]
To reiterate discussion in-channel.  At-door is $70 - no day passes are available.

**Comment by kitsuta** [comment]
It seems that the "full weekend pass" price is just the current badge price, so it will become $70 on Thursday. We still need to remove one-day badges, though.
