### ISSUE TITLE
ask for license plate and campsite on checkin form

### ISSUE THREAD

**Issue by binary1230** [magfest/magstock#83]
I recall last year we had these simple text fields here:

![image](https://cloud.githubusercontent.com/assets/5413064/15969382/df89c422-2efd-11e6-8467-0b32b824d5e2.png)

might interact with https://github.com/magfest/magstock/issues/70

**Comment by binary1230** [comment]
aha I see it, the file was renamed and the magstock-specific override isn't present.  we need to rename the magstock-specific version to check_in_form.html

I also see a bunch of extra JS in the magstock version that looks like it's been moved around to another file in base ubersystem.  we need to take a fine tooth comb to all of this to make sure it's working well.

**Comment by binary1230** [comment]
wait ok it's not even a simple rename, it looks like we extracted the form portion out to its own template and THAT's what we need to override/extend.  yea this will need a little surgery.  shouldn't be too bad though.

**Comment by kitsuta** [comment]
Yea, Eli did a complete overhaul of a lot of the registration templates.
