### ISSUE TITLE
As a staffer, I should be able to say I'm sleeping in the Manor House

### ISSUE THREAD

**Issue by kitsuta** [magfest/magstock#87]
On the confirmation page for staffing, IF I qualify for it, I should be able to select a "Manor House" housing option, since I may be planning to sleep in the staffing Manor house.

**Comment by binary1230** [comment]
I'm into this, though, it might be too late in the game to fix this this year.  Maybe, or at least I would consider it a low priority at this point.

**Comment by kitsuta** [comment]
Yes, this is for next year - at the very least, "qualifying" for the manor house needs to be defined by the Magstock folks, and they seem a bit busy at the moment.

**Comment by binary1230** [comment]
right now, lame version of this is fixed because you can assign staff to manor house and cabins via attendee.site_number

**Comment by Hachi05** [comment]
not necessary at this time. closing.
