### ISSUE TITLE
incomplete data for attendees in checkin form is not editable, should be?

### ISSUE THREAD

**Issue by binary1230** [magfest/magstock#94]
Looks like this:

![image](https://cloud.githubusercontent.com/assets/5413064/16139484/d3696a22-3415-11e6-930c-55858e4b0c64.png)

I recall that was supposed to look like text fields and it bugs the reg staffer to type in the missing info.  Current form does not have those fields and ... should? I vaguely recall it doing that

**Comment by kitsuta** [comment]
Hm, no, I don't think they ever did let you edit that. But yes, having them editable would be good.

**Comment by kitsuta** [comment]
Issue moved to [magfest/ubersystem #1874](https://github.com/magfest/ubersystem/issues/1874) via [**ZenHub**](https://www.zenhub.com/)
