### ISSUE TITLE
maybe not real: crash checkin form on license plate

### ISSUE THREAD

**Issue by binary1230** [magfest/magstock#96]
I think I just crashed the server by having /uber/registration/check_in return a 500 error

I did this by typing 'asdf' in the 'license plate' field on the quick checkin form.

Trying to repro

**Comment by binary1230** [comment]
wait i may not have run the DB migration, lemme check.

**Comment by binary1230** [comment]
I am going to chalk this up to me not running the db migration because thunderstorms or something.  ignore this.

**Comment by kitsuta** [comment]
Wait, this may give us good insight into how the app is crashing the server. We normally don't have something that's so easy to reproduce.

**Comment by binary1230** [comment]
continued discussion in https://github.com/magfest/ubersystem/issues/1881
